"wss://mppclone.com:8443":
  -
    _id: "âœ§ğ““ğ“”ğ“¥ ğ“¡ğ“¸ğ“¸ğ“¶âœ§"
    disable:
      - crown
    dmOnly:
      - bake
    set:
      color: "#1d0054"
      color2: "#000000"
  -
    _id: 'test/awkward'
    set:
      color: "#1d0054"
      color2: "#000000"
  -
    _id: 'test/fishing'
    set:
      color: "#1d0054"
      color2: "#000000"
  -
    _id: "Cosmic [indev]"
    set:
     color: "#1d0054"
     color2: "#000000"
