global:
  # Global prefixes can be used anywhere
  - '*'

mpp:
  # MPP prefixes can be configured for any channel
  -
    prefix: '&'
    channels:
      - 'âœ§ğ““ğ“”ğ“¥ ğ“¡ğ“¸ğ“¸ğ“¶âœ§'
  -
    prefix: '/'
    channels:
      - 'The Dev Channel'

discord:
  # Discord prefixes are only enabled for the Discord bot
  - '%'
